server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
      
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: elasticsearch-service
          uri: http://${ELASTICSEARCH_SERVICE_HOST:localhost}:${ELASTICSEARCH_SERVICE_PORT:8080}
          predicates:
            - Path=/**