server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
      
spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: iis-museum
          uri: http://${IIS_MUSEUM_HOST:localhost}:${IIS_MUSEUM_PORT:8081}
          predicates:
            - Path=/relational/**
        - id: elastic-service
          uri: http://${ELASTICSEARCH_SERVICE_HOST:localhost}:${ELASTICSEARCH_SERVICE_PORT:8080}
          predicates:
            - Path=/elastic/**

relational:
  host: ${IIS_MUSEUM_HOST:localhost}
  port: ${IIS_MUSEUM_PORT:8081}

elastic:
  host: ${ELASTICSEARCH_SERVICE_HOST:localhost}
  port: ${ELASTICSEARCH_SERVICE_PORT:8080}